// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8HjoI_ATnrZGAGVTN8KAMI0UmA8A-CTA',
    appId: '1:720374120759:web:fbd2482426ebebd3529ab2',
    messagingSenderId: '720374120759',
    projectId: 'petstagram-87440',
    authDomain: 'petstagram-87440.firebaseapp.com',
    storageBucket: 'petstagram-87440.appspot.com',
    measurementId: 'G-YWMC5JWZY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk1r2yv9upYab5mebxgxjUCUB2Ef_P8Aw',
    appId: '1:720374120759:android:2742b66230aba84e529ab2',
    messagingSenderId: '720374120759',
    projectId: 'petstagram-87440',
    storageBucket: 'petstagram-87440.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs5VMkle5ys_mEd12zR8nw3M36YDaMZ2s',
    appId: '1:720374120759:ios:6303de4de6ca3817529ab2',
    messagingSenderId: '720374120759',
    projectId: 'petstagram-87440',
    storageBucket: 'petstagram-87440.appspot.com',
    iosBundleId: 'com.example.petstagramPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs5VMkle5ys_mEd12zR8nw3M36YDaMZ2s',
    appId: '1:720374120759:ios:6303de4de6ca3817529ab2',
    messagingSenderId: '720374120759',
    projectId: 'petstagram-87440',
    storageBucket: 'petstagram-87440.appspot.com',
    iosBundleId: 'com.example.petstagramPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8HjoI_ATnrZGAGVTN8KAMI0UmA8A-CTA',
    appId: '1:720374120759:web:c5570b37f8e75ea8529ab2',
    messagingSenderId: '720374120759',
    projectId: 'petstagram-87440',
    authDomain: 'petstagram-87440.firebaseapp.com',
    storageBucket: 'petstagram-87440.appspot.com',
    measurementId: 'G-V6TTWWCSSJ',
  );
}
